# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  push:
    branches:
    - danser
  workflow_dispatch:
    inputs:
      skin:
        description: 'Direct link to skin'
        required: false
        default: 'https://cdn.discordapp.com/attachments/876678911990308924/879340922918297670/Blueberry-v1.3.2-mod-normal-trails.osk'
      replay:
        description: 'Direct link to osr file'
        required: false
        default: 'https://cdn.discordapp.com/attachments/876678911990308924/876678956529639454/Akane_Butterfly_-_Imperial_Circus_Dead_Decadence_-_Uta_Poetry_2021-06-02_Osu.osr'
      beatmapOverwrite:
        description: 'Direct link to osu file if custom map'
        required: false
        default: ''
      beatmapsetOverwrite:
        description: 'Beatmapset ID if custom map'
        required: false
        default: ''
      beatmapsetlinkOverwrite:
        description: 'Beatmapset link if custom map'
        required: false
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install deps
        run: |
          sudo apt-get -qq -o=Dpkg::Use-Pty=0 -y update;
          sudo apt-get -qq -o=Dpkg::Use-Pty=0 -y install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libswresample-dev libswscale-dev;
      - name: Render
        env:
          API_KEY: ${{ secrets.OSU_API_KEY }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK }}
          REPLAY_URL: ${{ github.event.inputs.replay }}
          SET_ID: ${{ github.event.inputs.beatmapsetOverwrite }}
          OVERWRITE_BEATMAPSET_LINK: ${{ github.event.inputs.beatmapsetlinkOverwrite }}
          OVERWRITE_MAP_LINK: ${{ github.event.inputs.beatmapOverwrite }}
          SKIN_URL: ${{ github.event.inputs.skin }}
        run: |
          Xvfb :1 &
          export DISPLAY=:1

          NODE_ENV=development yarn;
          yarn ts-node src/index.ts
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: video # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: work/video/video.mp4
          # The desired behavior if no files are found using the provided path.

