# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  push:
    branches:
    - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        run: git clone https://github.com/uyitroa/osr2mp4-core;
      - name: Install deps
        run: |
          sudo apt-get -qq -o=Dpkg::Use-Pty=0 -y update;
          sudo apt-get -qq -o=Dpkg::Use-Pty=0 -y install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libswresample-dev libswscale-dev;
          cd osr2mp4-core; cd osr2mp4/; python install.py; pip install Pillow-SIMD cython;
      - name: Prepare ImageProcess
        run: cd osr2mp4-core; cd osr2mp4/ImageProcess/Curves/libcurves/; python setup.py build_ext --inplace;
      - name: Prepare VideoProcess
        run: cd osr2mp4-core; cd osr2mp4/VideoProcess/FFmpegWriter/; python setup.py build_ext --inplace;
          
